# Makefile: Compilação dos testes

all:        insertOptions_test.exe

insertOptions_test.exe:        insertOptions_test.c
        gcc -o insertOptions_test insertOptions_test.c Unity/unity.c testFunctions/insertOptions.c
	./insertOptions_test.exe
