name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: gcc -o tests/insertOptions_test tests/insertOptions_test.c tests/Unity/unity.c tests/testFunctions/insertOptions.c
    
    - name: Test
      run: tests/insertOptions_test.exe